server:
  port: 8185

spring:
  application:
    name: gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user
          uri: lb://USER/
          predicates:
            - Path=/api/v1/user/**

        - id: user-auth
          uri: lb://USER/
          predicates:
            - Path=/api/v1/auth/**
#
        - id: event
          uri: lb://EVENT/
          predicates:
            - Path=/api/v1/event/**




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8181/eureka
