server:
  port: 8185

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user
          uri: http://user
          predicates:
            - Path=/api/v1/user/**
            - Path=/api/v1/auth/**

        - id: event
          uri: lb://event
          predicates:
            - Path=/api/v1/event/**



  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8181/eureka
