server:
  port: 8186
  servlet:
    session.timeout: 1m
management:
  endpoints:
    web:
      exposure:
        include: busrefresh,health,info,refresh

spring:
  application:
    name: config
  sleuth:
    enabled: false
    reactor:
      enabled: false
    web:
      enabled: false
    async:
      enabled: false
      client:
        template:
          enabled: false
  zipkin:
    enabled: false
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  security:
    user:
      name: ${CFG_SERVER_USER}
      password: ${CFG_SERVER_PWD}

  cloud:
    config:
      server:
        git:
          uri: ${SPRING_CONFIG_URI}
          username: ${SPRING_CONFIG_USR}
          password: ${SPRING_CONFIG_PWD}
          clone-on-start: true
          default-label: main
      bus:
        enabled: true
        refresh:
          enabled: true