server:
  port: 8186

management:
  endpoints:
    web:
      exposure:
        include: refresh

spring:
  application:
    name: config
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  cloud:
    config:
      server:
        git:
          uri: ${SPRING_CONFIG_URI}
          username: ${SPRING_CONFIG_USR}
          password: ${SPRING_CONFIG_PWD}
          clone-on-start: true
          default-label: main
      bus:
        enabled: true
        refresh:
          enabled: true