server:
  port: 9100
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
spring:
  application:
    name: MEET-GATEWAY
  cloud:
    gateway:
      routes:
        - id : user_ws_r
          uri: lb://USER-REG
          predicates:
            - Path=/api/register/**
            - Method=GET,POST
          filters:
            - RewritePath=/api/register/(?<segment>.*), /reg/$\{segment}
        - id : pwd_res_r
          uri: lb://PWD-RESET
          predicates:
            - Path=/api/password/reset/**
            - Method=GET,POST,PUT
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id : user_ws_login
          uri: lb://USER-LOGIN
          predicates:
            - Path=/api/auth/**
            - Method=GET,POST
          filters:
            - RewritePath=/api/(?<segment>.*), /auth/$\{segment}

