server:
  port: 9100
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true

spring:
  application:
    name: MEET-GATEWAY

  cloud:
    loadbalancer:
      ribbon:
        enabled:false:

    gateway:
      routes:
        - id : user_ws_r
          uri: lb://USER-REG
          predicates:
            - Path=/api/register/**
            - Method=GET,POST
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: user_ws_login
            uri: lb://USER-LOGIN
            predicates:
              - Path=/api/auth/**
              - Method=GET,POST
            filters:
              - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id : pwd_res_r
          uri: lb://PWD-RESET
          predicates:
            - Path=/api/password/reset/**
            - Method=GET,POST,PUT
            - Header=Authorization, Bearer {.*}
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - AuthorizationFilter
        - id : usr_event_res_r
          uri: lb://USER-MEET-EVENT
          predicates:
            - Path=/api/event/**
            - Method=GET,POST,PUT,DELETE
            - Header=Authorization, Bearer {.*}
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - AuthorizationFilter
        - id : usr_profile_res_r
          uri: lb://USER-PROFILE
          predicates:
            - Path = /api/user/profile/**
            - Method = GET,POST,PUT,DELETE
            - Header=Authorization, Bearer {.*}
          filters:
            - RewritePath=/api/user/(<segment>.*), /$\{segment}
            - AuthorizationFilter


