server:
  port: 8183

spring:
  application:
    name: gateway
    queue:
      notif: "NOTIF_MQ"
  config:
    import: configserver:http://${CONFIG_SERVER_HOST:localhost}:8186/
  cloud:
    config:
      profile: ${SPRING_CLOUD_PROFILES_ACTIVE:dev}
      fail-fast: true


  datasource:
    username: "zil"
    url: "jdbc:postgresql://localhost:5432/event"
    password: "password"
    driver-class-name: org.postgresql.Driver
    #    platform: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

