spring:
  application:
    name: notification
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  zipkin:
    base-url: http://localhost:9411
server:
  port: 8184

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8181/eureka