server:
  port: 8184

spring:
  application:
    name: notification
    queue:
      notif: "NOTIF_MQ"
  config:
    import: configserver:${CONFIG_SERVER_HOST:http://localhost}:8186/
  cloud:
    config:
      profile: ${SPRING_CLOUD_PROFILES_ACTIVE:dev}
      username: ${CONFIG_SERVER_USER:meat}
      password: ${CONFIG_SERVER_PWD:meat}
      fail-fast: true
