server:
  port: 8184

spring:
  application:
    name: notification
    queue:
      notif: "NOTIF_MQ"
  config:
    import: configserver:http://${CONFIG_SERVER_HOST:localhost}:8186/
  cloud:
    config:
      profile: ${SPRING_CLOUD_PROFILES_ACTIVE:dev}
      fail-fast: true
