server:
  port: 8185

spring:
  application:
    name: gateway
  zipkin:
    base-url: http://localhost:9411
  jwt:
    secret:
      token: "c5de5ad1f4d869618dd55dc850f29ec405cdf07d972862992722155c8d1880519593fea0a04d4a3ee87ad5931e77cebad06ce93f25ceab3ad2e0f07c6582877f"
    ttl: 120
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user-auth
          uri: lb://USER/
          predicates:
            - Path=/api/v1/auth/**

        - id: user
          uri: lb://USER/
          predicates:
            - Path=/api/v1/user/**
          filters:
            - AuthorizationFilter

        - id: event
          uri: lb://EVENT/
          predicates:
            - Path=/api/v1/event/**
          filters:
            - AuthorizationFilter


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8181/eureka
