server:
  port: 8185

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user-auth
          uri: lb://USER/
          predicates:
            - Path=/api/v1/auth/**

        - id: user
          uri: lb://USER/
          predicates:
            - Path=/api/v1/user/**

        - id: event
          uri: lb://EVENT/
          predicates:
            - Path=/api/v1/event/**
          filters:
            - AuthorizationFilter
