server:
  port: 8183

spring:
  application:
    name: event
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue:
      notif: "NOTIF_MQ"
  datasource:
    username: "zil"
    url: "jdbc:postgresql://localhost:5432/event"
    password: "password"
    driver-class-name: org.postgresql.Driver
    #    platform: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8181/eureka

