server:
  port: 0

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,timelimiters,timelimiterevents
  endpoint:
    health:
      show-details: always
resilience4j:
  instances:
    getUserValidConfirmation:
      timeoutDuration: 3s
  circuitbreaker:
    instances:
      eventActions:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      getUserValidConfirmation:
        registerHealthIndicator: false
        maxRetryAttempts: 2
        waitDuration: 2s


spring:
  application:
    name: event
    queue:
      notif: "NOTIF_MQ"
  config:
    import: configserver:${CONFIG_SERVER_HOST:http://localhost}:8186/
  cloud:
    config:
      profile: ${SPRING_CLOUD_PROFILES_ACTIVE:dev}
      username: ${CONFIG_SERVER_USER:meat}
      password: ${CONFIG_SERVER_PWD:meat}
      fail-fast: true



  datasource:
    username: ${PG_USER:zil}
    url: ${PG_URL:jdbc:postgresql://localhost:5432/user}
    password: ${PG_PWD:password}
    driver-class-name: org.postgresql.Driver
    #    platform: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

