spring:
  application:
    name: user
  config:
    import: configserver:${CONFIG_SERVER_HOST:http://localhost}:8186/
  cloud:
    config:
      profile: ${SPRING_CLOUD_PROFILES_ACTIVE:dev}
      username: ${CONFIG_SERVER_USER:meat}
      password: ${CONFIG_SERVER_PWD:meat}
      fail-fast: true
  datasource:
    username: ${PG_USER:zil}
    url: ${PG_URL:jdbc:postgresql://localhost:5432/user}
    password: ${PG_PWD:password}
    driver-class-name: org.postgresql.Driver
  #    platform: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson.serialization.fail-on-empty-beans: false